// pdx i18n — compile-time i18n tooling: extract keys, generate typed keys, validate dictionaries.

import { defineCommand } from 'citty';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { validateIcu } from '@pdxui/core/i18n';
import { loadConfigOrExit, resolveConfig } from '../config/loader';
import { logger } from '../utils/logger';
import { scanUsedKeys, loadDictionaries, buildReport, nestKeys, DEFAULT_DICT_GLOBS } from '../i18n/keys';

// ─── i18n extract ──────────────────────────────────────────────────
const extract = defineCommand({
    meta: { name: 'extract', description: 'Scan .pdx/.ts for $t() keys → translation template JSON' },
    args: {
        output: { type: 'string', default: 'translations/template.json', description: 'Output path (relative to the project root)' },
        json: { type: 'boolean', default: false, description: 'Print to stdout instead of writing a file' },
    },
    async run({ args }) {
        const { root } = await ctx();
        const { keys: used } = await scanUsedKeys(root);
        if (used.size === 0) { logger.info('No $t() keys found'); return; }

        const template = JSON.stringify(nestKeys([...used.keys()]), null, 2);
        if (args.json) { console.log(template); return; }

        const outPath = join(root, args.output as string);
        mkdirSync(dirname(outPath), { recursive: true });
        writeFileSync(outPath, template + '\n', 'utf-8');
        logger.success(`Extracted ${used.size} keys → ${outPath}`);
    },
});

// ─── i18n types ────────────────────────────────────────────────────
const types = defineCommand({
    meta: { name: 'types', description: 'Generate i18n-keys.d.ts so $t() is type-checked against known keys' },
    args: {
        locale: { type: 'string', default: 'en', description: 'Source-of-truth locale for the key set' },
        output: { type: 'string', default: 'i18n-keys.d.ts', description: 'Output path (relative to the project root)' },
    },
    async run({ args }) {
        const places = await ctx();
        const { root } = places;
        const search = dictSearch(args as { dicts?: string }, places);
        const { dictionaries: dicts } = await loadDictionaries(search.bases, search.globs);
        // Prefer the chosen locale; otherwise the union of every locale's keys; otherwise used keys.
        const chosen = dicts.find(d => d.locale === args.locale);
        let keys: string[];
        if (chosen) {
            keys = [...chosen.messages.keys()];
        } else if (dicts.length) {
            keys = [...new Set(dicts.flatMap(d => [...d.messages.keys()]))];
            logger.warn(`No "${args.locale}" dictionary — using the union of ${dicts.length} locales`);
        } else {
            keys = [...(await scanUsedKeys(root)).keys.keys()];
            logger.warn('No dictionaries found — typing against the keys used in source');
        }
        if (keys.length === 0) { logger.info('No keys to type'); return; }

        const body = keys.sort().map(k => `        ${JSON.stringify(k)}: true;`).join('\n');
        const dts = `// AUTO-GENERATED by \`pdx i18n types\`. Do not edit by hand.\n`
            + `// Augments $t()'s key type so unknown keys are a build error.\n`
            + `import '@pdxui/core';\n\n`
            + `declare module '@pdxui/core' {\n    interface PdxMessages {\n${body}\n    }\n}\n`;
        const outPath = join(root, args.output as string);
        mkdirSync(dirname(outPath), { recursive: true });
        writeFileSync(outPath, dts, 'utf-8');
        logger.success(`Typed ${keys.length} keys → ${outPath}`);
    },
});

// ─── i18n validate ─────────────────────────────────────────────────
const validate = defineCommand({
    meta: { name: 'validate', description: 'Report missing/orphan keys per locale + malformed ICU messages' },
    args: {
        strictOrphans: { type: 'boolean', default: false, description: 'Treat orphan (unused) keys as errors too' },
        dicts: { type: 'string', description: `Glob for the dictionaries, relative to the project (default: ${DEFAULT_DICT_GLOBS.join(', ')})` },
    },
    async run({ args }) {
        const places = await ctx();
        const { keys, prefixes } = await scanUsedKeys(places.root);
        const search = dictSearch(args as { dicts?: string }, places);
        const { dictionaries: dicts, malformed, searched } = await loadDictionaries(search.bases, search.globs);
        if (dicts.length === 0 && malformed.length === 0) {
            // Naming every place that was tried, because "no dictionaries under src/translations"
            // read as "this tool has one convention" and sent the reporter to move their files.
            logger.warn(`No dictionaries found. Looked in:`);
            searched.forEach(place => logger.log(`    ${place}`));
            logger.log('    Point at them with --dicts <glob> if they live somewhere else.');
            return;
        }

        let errors = 0;
        let warnings = 0;
        // Malformed JSON is a hard error, not a silent skip — CI must catch a broken locale file.
        for (const m of malformed) { errors++; logger.error(`[invalid JSON] ${m.file}: ${m.error}`); }
        for (const dict of dicts) {
            const { missing, orphan, componentStrings, unmatchedPrefixes } = buildReport(keys, prefixes, dict.messages);
            const icu: string[] = [];
            for (const [k, v] of dict.messages) {
                const err = validateIcu(v);
                if (err) icu.push(`${k}: ${err}`);
            }

            const clean = missing.length === 0 && orphan.length === 0 && icu.length === 0
                && componentStrings.length === 0 && unmatchedPrefixes.length === 0;
            if (clean) { logger.success(`[${dict.locale}] OK — ${dict.messages.size} keys`); continue; }

            logger.log('');
            logger.log(`[${dict.locale}] ${dict.file}`);
            if (missing.length) { errors += missing.length; logger.error(`  ${missing.length} missing (used but not translated):`); missing.forEach(k => logger.log(`    - ${k}`)); }
            if (componentStrings.length) {
                // A different registry, not a missing entry.
                errors += componentStrings.length;
                logger.error(`  ${componentStrings.length} asked of $t but owned by the component string registry:`);
                componentStrings.forEach(k => logger.log(`    - ${k} → set it with setLocaleStrings('${k.split('.')[0]}', …), not in this dictionary`));
            }
            if (icu.length) { errors += icu.length; logger.error(`  ${icu.length} malformed ICU:`); icu.forEach(e => logger.log(`    - ${e}`)); }
            if (unmatchedPrefixes.length) {
                warnings += unmatchedPrefixes.length;
                logger.warn(`  ${unmatchedPrefixes.length} composed key(s) whose prefix translates nothing:`);
                unmatchedPrefixes.forEach(p => logger.log(`    - $t('${p}' + …) — no entry starts with "${p}"`));
            }
            if (orphan.length) {
                if (args.strictOrphans) errors += orphan.length; else warnings += orphan.length;
                logger[args.strictOrphans ? 'error' : 'warn'](`  ${orphan.length} orphan (translated but unused):`);
                orphan.forEach(k => logger.log(`    - ${k}`));
            }
        }

        logger.log('');
        if (errors > 0) { logger.error(`i18n validation failed: ${errors} error(s), ${warnings} warning(s)`); process.exitCode = 1; }
        else logger.success(`i18n validation passed${warnings ? ` (${warnings} warning(s))` : ''}`);
    },
});

/** Resolve the project root once per invocation. */
async function ctx(): Promise<{ root: string; cwd: string }> {
    const cwd = process.cwd();
    const resolved = resolveConfig(await loadConfigOrExit(cwd), cwd);
    return { root: resolved.root, cwd };
}

/**
 * Where to look for dictionaries: an explicit `--dicts` glob, or the conventions, under the source
 * root AND the project root. `root` is `<cwd>/src` by convention, and a dictionary is as often
 * beside the app as inside it — searching only one of the two leaves every other convention
 * unfound.
 */
function dictSearch(args: { dicts?: string }, places: { root: string; cwd: string }) {
    const globs = args.dicts ? [args.dicts] : DEFAULT_DICT_GLOBS;
    return { bases: [places.root, places.cwd], globs };
}

export default defineCommand({
    meta: { name: 'i18n', description: 'i18n tooling — extract keys, generate typed keys, validate dictionaries' },
    subCommands: { extract, types, validate },
});
