// Scoped Slot — enables parent to project content that receives data from the child.
// Reads scope data FIRST, then swaps DOM atomically to avoid race conditions.

import { effect } from '../reactivity/signal';
import { placePartNode } from './part-nodes';

export type SlotFunction = (scope: Record<string, unknown>) => Node | DocumentFragment;

/**
 * Create a carrier element that transports a slot function from parent to child.
 * The child's _projectSlots() extracts this during mount.
 * Generated by the compiler for @slot(name, { vars }) { body } directives.
 */
export function slotCarrier(name: string, fn: SlotFunction): HTMLElement {
    const el = document.createElement('pdx-slot');
    el.style.display = 'none';
    const carrier = el as HTMLElement & { __pdxSlot?: SlotFunction; __pdxSlotName?: string };
    carrier.__pdxSlot = fn;
    carrier.__pdxSlotName = name;
    return el;
}

/**
 * Render a scoped slot. If the parent provided a slot function, call it with scope data.
 * Otherwise, render the default content.
 */
export function renderSlot(
    slots: Record<string, SlotFunction> | undefined,
    name: string,
    scopeFn: (() => Record<string, unknown>) | null,
    defaultFn: () => Node | DocumentFragment
): DocumentFragment {
    const frag = document.createDocumentFragment();
    const start = document.createComment(`slot:${name}`);
    const end = document.createComment(`/slot:${name}`);
    frag.appendChild(start);
    frag.appendChild(end);

    const slotFn = slots?.[name];

    if (!slotFn) {
        // No parent slot provided — render default content (static, one-shot)
        const content = defaultFn();
        const parent = end.parentNode ?? frag;
        if (content instanceof DocumentFragment) {
            const nodes = Array.from(content.childNodes);
            for (const n of nodes) parent.insertBefore(n, end);
        } else {
            parent.insertBefore(content, end);
        }
        return frag;
    }

    // Parent provided a slot function — render reactively with scope data
    let currentNodes: Node[] = [];

    effect(() => {
        const parent = end.parentNode;
        if (!parent) return;

        // Read scope data FIRST (tracks signal dependencies)
        const scope = scopeFn ? scopeFn() : {};

        // THEN render new content
        const content = slotFn(scope);
        const newNodes = content instanceof DocumentFragment
            ? Array.from(content.childNodes)
            : [content];

        // THEN swap DOM atomically: remove old, insert new
        for (const n of currentNodes) {
            if (n.parentNode === parent) parent.removeChild(n);
        }
        for (const n of newNodes) placePartNode(parent, n, end);
        currentNodes = newNodes;
    });

    return frag;
}
