// The defect half of the diagnostics catalog: something is wrong, and the output shows it. See catalog.ts.

import type { DiagnosticEntry } from './catalog';

/** A .pdx with this template and this setup script — the shape every example below uses. */
const pdx = (template: string, script: string): string =>
    `<template>\n  ${template}\n</template>\n<script setup>\n${script}\n</script>\n`;

const T = 'packages/compiler/tests/';

export const DEFECTS: Record<string, DiagnosticEntry> = {
    PDX_RAW_INTERPOLATION: {
        severity: 'warn', category: 'defect', fixable: true,
        summary: 'A `${…}` in the template markup.',
        explanation: '`${}` is evaluated once, when the template is built, so the text or attribute never updates. In a template, text is `{{ expr }}` and an attribute is bound with `:attr="expr"`.',
        fix: 'Text: `{{ name }}`. Attribute: `:title="name"`.',
        example: { bad: pdx('<p title="${n}">x</p>', 'let n = $signal(1);'), good: pdx('<p :title="n">x</p>', 'let n = $signal(1);') },
    },
    PDX_RAW_INTERPOLATION_IN_BINDING: {
        severity: 'error', category: 'defect', fixable: true,
        summary: 'A `${…}` inside the value of a bound attribute (`:x`, `::x`, `@x`).',
        explanation: 'The value of a bound attribute is already an expression. `${x}` in it is written into the module as it is, and a production build (inline bindings) does not parse — the compile stops at the line instead.',
        fix: 'Drop the `${ }`: `:label="${x}"` → `:label="x"`. A template literal inside the expression (`` :class="`btn-${size}`" ``) is fine.',
        example: { bad: pdx('<p :title="${n}">x</p>', 'let n = $signal(1);'), good: pdx('<p :title="n">x</p>', 'let n = $signal(1);') },
    },
    PDX_NON_REACTIVE: {
        severity: 'warn', category: 'defect', fixable: true,
        summary: 'A plain `let` the template reads and the script changes.',
        explanation: 'Only `$signal` and `$derived` are tracked. A plain variable is read once: the template keeps showing its first value.',
        fix: 'Declare it with `$signal`: `let count = $signal(0);`.',
        reproducedIn: `${T}validate.test.ts`,
    },
    PDX_SCRIPT_SYNTAX_ERROR: {
        severity: 'error', category: 'defect',
        summary: 'The `<script setup>` does not parse.',
        explanation: 'A syntax error in the setup would reach the generated module as broken code. It is reported with its position in the script.',
        fix: 'Fix the syntax at the reported line.',
        reproducedIn: `${T}validate.test.ts`,
    },
    PDX_UNKNOWN_DECLARATION: {
        severity: 'error', category: 'defect',
        summary: 'A known `@` declaration written in a shape the compiler does not recognise.',
        explanation: 'The line is dropped and nothing is generated for it; left in the body it would make the module unparseable.',
        fix: 'Write it in the shape the hint shows for that keyword.',
        reproducedIn: `${T}validate.test.ts`,
    },
    PDX_TS_UNSUPPORTED: {
        severity: 'error', category: 'defect',
        summary: 'TypeScript in a `.pdx` script that has a runtime of its own: an enum, a namespace, a parameter property, `import = require()`.',
        explanation: "The compiler erases a script's TypeScript, types only, keeping every position. These constructs are not types: an `enum` and a `namespace` create objects, a parameter property assigns a field, `import =` loads a module. There is no erasure that keeps what they do, and the compile stops at them instead of shipping code the browser rejects.",
        fix: 'Write it as JavaScript: a frozen object for an enum (`const Color = Object.freeze({ Red: 0 })`), a module for a namespace, an assignment in the constructor for a parameter property, an `import` for `import =`.',
        reproducedIn: `${T}erase-types.test.ts`,
    },
    PDX_DUPLICATE_SCRIPT: {
        severity: 'error', category: 'defect',
        summary: 'A second `<script>` block in a `.pdx`.',
        explanation: 'A `.pdx` has one `<script>`. The parser reads the first; a second would be dropped without a word — its declarations surfacing only as undeclared names in the template, its statements (an `onMount(…)`) never running. So the compile stops at it, naming its line.',
        fix: 'Move its code into the first `<script setup>`.',
        reproducedIn: `${T}duplicate-blocks.test.ts`,
    },
    PDX_DUPLICATE_TEMPLATE: {
        severity: 'error', category: 'defect',
        summary: 'A second `<template>` block in a `.pdx`.',
        explanation: 'A `.pdx` has one `<template>`; the parser reads the first, and the markup of a second would never render. So the compile stops at it, naming its line.',
        fix: 'Move its markup into the first `<template>`.',
        reproducedIn: `${T}duplicate-blocks.test.ts`,
    },
    PDX_STORE_EXPORT: {
        severity: 'error', category: 'defect',
        summary: 'An `export` in a `@store` module that reads a name the store owns.',
        explanation: "A `@store` module's exports are emitted at module level, outside the store's factory, where the store's signals and functions do not exist: the export would throw a ReferenceError when the module loads. An export that reads none of them — a constant, a helper — is moved out as it is.",
        fix: 'Read the store through its hook (`useMenu().selected`), or move the export to its own module.',
        reproducedIn: `${T}store-module-exports.test.ts`,
    },
    PDX_DUP_DECLARATION: {
        severity: 'error', category: 'defect',
        summary: 'The same name declared twice at the top of the script: runes, `@prop`, functions, classes, plain variables.',
        explanation: 'The compiled component keeps one of them, and nothing says which. A signal is renamed in the output, so a `$signal` and a `function` of one name do not even clash as JavaScript would: the template sees whichever the component returns last.',
        fix: 'Rename one, or remove the one you do not mean.',
        reproducedIn: `${T}duplicate-declarations.test.ts`,
    },
    PDX_PROP_NO_TYPE: {
        severity: 'error', category: 'defect',
        summary: '`@prop` without a type annotation.',
        explanation: 'The prop needs a type to coerce attributes and to generate its `.d.ts`; the declaration is not generated.',
        fix: "`@prop label: string = 'Hello';`",
        example: { bad: pdx('<p>{{ label }}</p>', '@prop label;'), good: pdx('<p>{{ label }}</p>', "@prop label: string = 'Hello';") },
    },
    PDX_PROP_INVALID_TYPE: {
        severity: 'warn', category: 'defect',
        summary: "A `@prop`'s type annotation is malformed.",
        explanation: 'Unbalanced brackets or a trailing `|`, `&` or `,` — the generated `.d.ts` may be invalid.',
        fix: 'Balance the type: `@prop items: Array<string> = [];`',
        reproducedIn: `${T}prop-type-validation.test.ts`,
    },
    PDX_PROP_TYPE_MISMATCH: {
        severity: 'warn', category: 'defect',
        summary: "A `@prop`'s default does not match its type.",
        explanation: 'A `number` prop with a string default is coerced at the first attribute write, and reads differently before and after.',
        fix: 'Make the default match the type, or the type match the default.',
        reproducedIn: `${T}validate.test.ts`,
    },
    PDX_DUP_PROP: {
        severity: 'error', category: 'defect',
        summary: 'The same `@prop` declared twice.',
        explanation: 'Two declarations of one prop: only one is generated.',
        fix: 'Remove the duplicate `@prop`.',
        example: {
            bad: pdx('<p>{{ a }}</p>', "@prop a: string = 'x';\n@prop a: string = 'y';"),
            good: pdx('<p>{{ a }}</p>', "@prop a: string = 'x';"),
        },
    },
    PDX_MALFORMED_EVENT: {
        severity: 'error', category: 'defect',
        summary: '`@event` written in a shape the compiler does not recognise.',
        explanation: 'No emitter is generated for it, so calling it does nothing.',
        fix: '`@event saved: number;` — a lowercase name, a colon, a payload type.',
        example: { bad: pdx('<p>x</p>', '@event (saved): number;'), good: pdx('<p>x</p>', '@event saved: number;') },
    },
    PDX_DUP_EVENT: {
        severity: 'error', category: 'defect',
        summary: 'The same `@event` declared twice.',
        explanation: 'Two declarations of one event: only one emitter is generated.',
        fix: 'Remove the duplicate `@event`.',
        example: {
            bad: pdx('<p>x</p>', '@event changed: number;\n@event changed: number;'),
            good: pdx('<p>x</p>', '@event changed: number;'),
        },
    },
    PDX_EVENT_NAME_CASE: {
        severity: 'warn', category: 'defect', fixable: true,
        summary: 'An `@event` name with an uppercase letter.',
        explanation: "HTML lowercases attribute names, so a parent's `@savedItem=\"…\"` listens for `saveditem` and never hears it.",
        fix: 'Use a lowercase name: `@event saveditem: Item;`. The fix renames it in the script; when the template uses the name, the rename is left to you.',
        reproducedIn: `${T}event-name-case.test.ts`,
    },
    PDX_EXPOSE_UNDECLARED: {
        severity: 'error', category: 'defect',
        summary: '`@expose` names something the component does not declare.',
        explanation: 'There is nothing to expose: the method a parent calls does not exist.',
        fix: 'Declare it first (`function close() { … }`), or remove it from `@expose`.',
        reproducedIn: `${T}validate.test.ts`,
    },
    PDX_CIRCULAR_DERIVED: {
        severity: 'error', category: 'defect',
        summary: '`$derived` values that depend on each other in a cycle.',
        explanation: 'A cycle has no first value to compute; the runtime breaks it and the values are wrong.',
        fix: 'Make one of them a `$signal` that the other writes.',
        reproducedIn: `${T}validate.test.ts`,
    },
    PDX_UNUSED_REACTIVE: {
        severity: 'info', category: 'defect',
        summary: 'A `$signal` or `$derived` that nothing reads.',
        explanation: 'Reactive state no template, effect or function reads costs a subscription and says nothing.',
        fix: 'Remove it, or prefix it with `_` if it is kept on purpose.',
        reproducedIn: `${T}declared-shadows-global.test.ts`,
    },
    PDX_REWRITE_FALLBACK: {
        severity: 'warn', category: 'defect',
        summary: 'A fragment of the setup the signal rewriter could not parse.',
        explanation: 'The fragment is kept as written, so a signal read inside it is not called and is not reactive.',
        fix: 'Fix the syntax, or move the fragment out of the setup body.',
        reproducedIn: `${T}diagnostic-channel.test.ts`,
    },
    PDX_UNRESOLVED_COMPONENT: {
        severity: 'warn', category: 'defect', fixable: true,
        summary: 'A custom-element tag that no component package and no project component defines.',
        explanation: 'The custom element is never registered: it renders as an empty unknown element, with no console error. Component packages are the dependencies whose package.json declares `customElements` (@pdxui/ui and @pdxui/router among them); project components are the .pdx files under `src/`, `pages/` and `pdx({ components })`. The hint lists what was searched.',
        fix: 'Check the spelling — when one known tag is within 2 edits the message names it, and the fix renames the tag; otherwise add the package that defines it to package.json, or import the module that registers it.',
        reproducedIn: `${T}diagnostic-channel.test.ts`,
    },
    PDX_UNKNOWN_PROP: {
        severity: 'warn', category: 'defect', fixable: true,
        summary: 'A bound name the component does not declare as a prop.',
        explanation: 'The value lands on an element property nothing reads.',
        fix: 'Use the declared prop — the hint names the closest one. The fix renames it when one declared prop is within 2 edits.',
        reproducedIn: `${T}bound-prop-names.test.ts`,
    },
    PDX_PROP_NAME_CASE: {
        severity: 'warn', category: 'defect', fixable: true,
        summary: 'A bound prop written in lowercase that matches a camelCase prop.',
        explanation: 'It reaches the prop only because the compiler knows the component; written for an unknown element it would not.',
        fix: 'Write the declared name: `:maxItems`.',
        reproducedIn: `${T}bound-prop-names.test.ts`,
    },
    PDX_INVALID_ENUM_VALUE: {
        severity: 'warn', category: 'defect',
        summary: 'A static or literal attribute value (`size="huge"`, `:size="\'huge\'"`) outside the values its prop declares.',
        explanation: 'A component receives a value its type does not admit and falls back to its default, silently.',
        fix: 'Use one of the allowed values the hint lists.',
        reproducedIn: `${T}undeclared-refs-and-enums.test.ts`,
    },
    PDX_EMPTY_FOR: {
        severity: 'warn', category: 'defect',
        summary: 'An `@for` with an empty body.',
        explanation: 'The loop renders nothing for every item.',
        fix: 'Put the row inside the block, or remove the loop.',
        example: {
            bad: pdx('@for (items as item; track item) {}', 'let items = $signal([1, 2]);'),
            good: pdx('@for (items as item; track item) { <p>{{ item }}</p> }', 'let items = $signal([1, 2]);'),
        },
    },
    PDX_AWAIT_NO_LOADING: {
        severity: 'info', category: 'defect',
        summary: '`@await` without a `@loading` block.',
        explanation: 'The user sees nothing while the promise is pending.',
        fix: 'Add `@loading { … }` with a placeholder.',
        reproducedIn: `${T}await-directive.test.ts`,
    },
    PDX_FETCH_INVALID: {
        severity: 'error', category: 'defect',
        summary: "`@fetch` without a valid `'METHOD /url'`.",
        explanation: 'The resource cannot be generated; dropping it silently would break the component with no message.',
        fix: "`@fetch users: 'GET /api/users' as User[];`",
        reproducedIn: `${T}fetch-directive-diagnostics.test.ts`,
    },
    PDX_TEMPLATE_NAME_NOT_PROVIDED: {
        severity: 'error', category: 'defect',
        summary: 'A legacy-mode template reads a name its script does not provide.',
        explanation: 'In the legacy mode the template sees what `defineProps` declares and what the top-level `return { … }` returns. A `const` the script declares and does not return reads as undefined — and a plain `<script>` with no rune is the legacy mode.',
        fix: 'Write `<script setup>`, which hands the template every name it declares — or add the name to the returned object.',
        reproducedIn: `${T}legacy-template-names.test.ts`,
    },
    PDX_FETCH_METHOD: {
        severity: 'error', category: 'defect',
        summary: '`@fetch` with a method other than GET.',
        explanation: '`@fetch` reads. A POST, PUT or DELETE written here used to compile to a GET of the same URL, and nothing said so.',
        fix: "For a read, `'GET /url'`. For a write, a `mutation()`.",
        reproducedIn: `${T}fetch-strict.test.ts`,
    },
    PDX_FETCH_TYPE_COLON: {
        severity: 'error', category: 'defect',
        summary: '`@fetch` with its type written after `:`.',
        explanation: 'The type is written with `as`. Written with `:` it was dropped, and the options block after it with it.',
        fix: "`@fetch users: 'GET /api/users' as User[];`",
        reproducedIn: `${T}fetch-strict.test.ts`,
    },
    PDX_FETCH_UNKNOWN_OPTION: {
        severity: 'error', category: 'defect',
        summary: '`@fetch` with an option `resource()` does not take.',
        explanation: 'The options block is handed to `resource()`, which ignores a key it does not know: a misspelled `stalTime` does nothing.',
        fix: 'Use one of `resource()`\'s options: key, staleTime, retry, tags, enabled, transform, onSuccess, onError, cache, stale.',
        reproducedIn: `${T}fetch-strict.test.ts`,
    },
    PDX_FETCH_NO_ERROR_UI: {
        severity: 'info', category: 'defect',
        summary: 'An `@fetch` whose error state the template never shows.',
        explanation: 'A failed request leaves the screen as it was, with nothing telling the user.',
        fix: "Show it: `@if (users.state() === 'error') { … }`.",
        example: {
            bad: pdx('<p>{{ users.value() }}</p>', "@fetch users: 'GET /api/users' as string[];"),
            good: pdx("@if (users.state() === 'error') { <p>Could not load</p> } <p>{{ users.value() }}</p>", "@fetch users: 'GET /api/users' as string[];"),
        },
    },
    PDX_FORM_NO_SUBMIT: {
        severity: 'info', category: 'defect',
        summary: 'A `@form` that nothing submits.',
        explanation: 'The form validates and holds values, and no `handleSubmit` sends them anywhere.',
        fix: 'Wire `form.handleSubmit(async (values) => { … })`, or hand the form to `<pdx-form :form>`.',
        reproducedIn: `${T}form-submit-warning.test.ts`,
    },
    PDX_FORM_ARRAY_RULES_IGNORED: {
        severity: 'warn', category: 'defect',
        summary: "Validation rules inside a `@form` array field.",
        explanation: 'A rule written on a row field is parsed and then dropped: rows are never validated.',
        fix: '`<pdx-field-list :item-fields="[{ name, required: true }]">`, which registers the rule as each row is added.',
        reproducedIn: `${T}form-directive.test.ts`,
    },
    PDX_FORM_FIELD_UNPARSED: {
        severity: 'warn', category: 'defect',
        summary: 'A `@form` field the compiler did not understand.',
        explanation: 'No field is generated, so the control bound to it swallows what is typed.',
        fix: 'Write the field as `name: type { rules }`, `name: string[]`, `name: { sub: type }` or `name: [{ sub: type }]`.',
        reproducedIn: `${T}form-list-field.test.ts`,
    },
    PDX_LEGACY_IN_SETUP: {
        severity: 'warn', category: 'defect',
        summary: 'A legacy marker (`defineProps`, `defineEmits`, a top-level `return`) in `<script setup>`.',
        explanation: 'With runes beside it, the marker does nothing; without runes, the file compiles in the legacy mode and any rune added later is inert.',
        fix: 'Remove the marker — `<script setup>` returns what it declares — or write plain `<script>` for a deliberately legacy file.',
        reproducedIn: `${T}validate.test.ts`,
    },
    PDX_PAGE_INVALID_PATH: {
        severity: 'error', category: 'defect',
        summary: "An `@page` path that does not start with '/'.",
        explanation: 'The route would never match an address.',
        fix: "`@page '/users';`",
        example: { bad: pdx('<p>x</p>', "@page 'users';"), good: pdx('<p>x</p>', "@page '/users';") },
    },
    PDX_PAGE_INVALID_CONSTRAINT: {
        severity: 'warn', category: 'defect',
        summary: 'A route param constraint that is not a known type.',
        explanation: 'The constraint is not applied, so the param matches anything.',
        fix: 'Use one of the constraints the hint lists: `:id(number)`.',
        reproducedIn: `${T}validate.test.ts`,
    },
    PDX_PAGE_EMPTY_CONSTRAINT: {
        severity: 'error', category: 'defect',
        summary: 'A route param with empty parentheses: `:id()`.',
        explanation: 'A constraint was meant and none was written.',
        fix: '`:id(number)`, or remove the parentheses.',
        reproducedIn: `${T}validate.test.ts`,
    },
    PDX_LOADER_NOT_FOUND: {
        severity: 'warn', category: 'defect',
        summary: '`@loader` names a function the script does not declare.',
        explanation: 'The route is registered without a loader, so the page renders with no data.',
        fix: 'Declare it: `async function loadUser() { … }`.',
        reproducedIn: `${T}route-label-fn.test.ts`,
    },
    PDX_LABEL_NOT_FOUND: {
        severity: 'warn', category: 'defect',
        summary: "A route's label names a function the script does not declare.",
        explanation: 'The route contributes no crumb to the breadcrumb.',
        fix: 'Declare it: `function crumb(params) { … }`, or write the crumb as a string.',
        reproducedIn: `${T}route-label-fn.test.ts`,
    },
    PDX_INLINE_NODE_UNSUPPORTED: {
        severity: 'warn', category: 'defect',
        summary: 'A template node the inline render path cannot compile.',
        explanation: 'The node would be left out of the production render. The warning makes a missing feature visible instead of silent.',
        fix: 'Build with `pdx({ inlineBindings: false })`, and report the node type.',
        unreachable: 'Every template node type has a case in the inline generator today (codegen-template-inline.ts `walk`); this is the net for the next type the parser learns.',
    },
    PDX_GLOBAL_SELECTOR: {
        severity: 'warn', category: 'defect',
        summary: '`:global()` in a style.',
        explanation: '`:global()` is not CSS, and the browser drops the whole rule. A scoped style already reaches the descendants a child component renders.',
        fix: 'Remove the wrapper: `:global(.x) .y` → `.x .y`.',
        reproducedIn: `${T}global-selector.test.ts`,
    },
    PDX_DOCUMENT_QUERY: {
        severity: 'warn', category: 'defect',
        summary: '`document.querySelector` (or a sibling) in a component (CD-A1).',
        explanation: 'It finds whatever matches in the whole page — another instance included — and nothing when the element is elsewhere.',
        fix: 'Bind the element with `:ref`; for a child component, ask it through `@expose`.',
        reproducedIn: `${T}design-checks.test.ts`,
    },
    PDX_PROP_WRITE: {
        severity: 'warn', category: 'defect',
        summary: 'A component writes one of its own props (CD-A2).',
        explanation: "The parent owns the prop: its next value overwrites the component's.",
        fix: 'Emit the new value with an `@event`; for a starting value, copy it into a `$signal`.',
        reproducedIn: `${T}design-checks.test.ts`,
    },
    PDX_LISTENER_LEAK: {
        severity: 'warn', category: 'defect',
        summary: 'An `addEventListener` on a global target with no matching removal (CD-D3).',
        explanation: 'The listener outlives the component and keeps acting on a screen that is gone.',
        fix: 'Add it in `onMount` and remove it in an `onDestroy` beside it.',
        reproducedIn: `${T}design-checks.test.ts`,
    },
    PDX_LIBRARY_INTERNALS: {
        severity: 'warn', category: 'defect',
        summary: "A style that targets a library component's internal class (CD-C2).",
        explanation: 'Internal classes are not an API: a rename in the library breaks the rule without a sound.',
        fix: "Use the component's props, variants or documented `--pdx-*` properties; if several pages need it, the component needs a prop.",
        reproducedIn: `${T}design-checks.test.ts`,
    },
    PDX_DERIVED_WRITE: {
        severity: 'warn', category: 'defect',
        summary: 'Code that writes into the object a `$derived` returned (CD-S2).',
        explanation: "The derived's next computation replaces the object, so the written value lies until something patches it again.",
        fix: 'Derive the field from its source; if a reader overrides it, it is a `$signal` reset by `$watch` on the source.',
        reproducedIn: `${T}design-checks-data-flow.test.ts`,
    },
    PDX_TAG_COLLISION_RESOLVER: {
        severity: 'warn', category: 'defect',
        summary: 'Two component files derive the same tag; the second is not auto-importable.',
        explanation: 'Only one of the two is registered by auto-import, and which one depends on scan order.',
        fix: "Rename one of the files, or give one an explicit `@tag 'pdx-other-name';`.",
        reproducedIn: `${T}resolver-collision-channel.test.ts`,
    },
    PDX_TAG_COLLISION: {
        severity: 'error', category: 'defect',
        summary: 'Two compiled `.pdx` files register the same tag (build error).',
        explanation: 'A custom element can be defined once; the second definition would throw in the browser.',
        fix: "Add `@tag 'pdx-unique-name';` to one of the files.",
        reproducedIn: `${T}resolver-collision-channel.test.ts`,
    },
    PDX_EMPTY_SOURCE: {
        severity: 'error', category: 'defect',
        summary: 'An empty `.pdx` file (build error).',
        explanation: 'An empty file would compile to a component that registers and renders nothing — indistinguishable from a working one. Usually a file read while it was being saved.',
        fix: 'Save the file again; if it really is empty, write its template.',
        reproducedIn: `${T}empty-source.test.ts`,
    },
    PDX_I18N_MISSING_KEY: {
        severity: 'warn', category: 'defect',
        summary: 'A translation key present in one locale and missing in another (`pdx check --i18n`).',
        explanation: 'The screen in that locale shows the key, or the fallback language, where a translation was meant.',
        fix: 'Add the key to the locale file the message names.',
        reproducedIn: 'packages/cli/tests/check-command.test.ts',
    },
    PDX_TS: {
        severity: 'error', category: 'defect',
        summary: 'A TypeScript error in the script or a template expression (`pdx check --types`).',
        explanation: 'The type-check the editor shows, run headless: the script and every template expression are checked with the runes typed as their values, and the TypeScript code is in `tsCode`. The compiler builds the file anyway; this is the error the editor underlines.',
        fix: 'Fix the type the message names — the finding is at its line in the .pdx.',
        reproducedIn: 'packages/cli/tests/check-types.test.ts',
    },
    PDX_IGNORE_WITHOUT_REASON: {
        severity: 'error', category: 'defect',
        summary: 'A `pdx-ignore` comment that does not say why.',
        explanation: 'An exemption is a decision, and one without its reason cannot be reviewed or retired: it exempts nothing until the reason is written.',
        fix: 'Add the reason after a colon: `<!-- pdx-ignore PDX_COLOUR_LITERAL: a palette swatch -->`.',
        example: {
            bad: pdx('<!-- pdx-ignore PDX_RAW_INTERPOLATION -->\n  <p>x</p>', 'let a = $signal(1);'),
            good: pdx('<!-- pdx-ignore PDX_RAW_INTERPOLATION: shown as written -->\n  <p>x</p>', 'let a = $signal(1);'),
        },
    },
    PDX_IGNORE_UNUSED: {
        severity: 'warn', category: 'defect',
        summary: 'A `pdx-ignore` that silences nothing.',
        explanation: 'What it exempted is gone, or it sits on the wrong line. Left there, it would silence the next finding of that code without anyone deciding to. Reported by `pdx check`, which runs every check.',
        fix: 'Remove it, or move it to the line before the finding.',
        reproducedIn: 'packages/cli/tests/check-ignore.test.ts',
    },
    PDX_UNDECLARED_REF: {
        severity: 'error', category: 'defect', fixable: true,
        summary: 'A name the template reads that `<script setup>` does not declare.',
        explanation: 'At runtime the binding reads `undefined`, and a handler named this way does nothing when clicked; usually a misspelt signal, prop or function.',
        fix: 'Declare it, or fix the spelling — when one declared name is within 2 edits the message names it, and the fix renames the read.',
        example: { bad: pdx('<p>{{ coutn }}</p>', 'let count = $signal(0);'), good: pdx('<p>{{ count }}</p>', 'let count = $signal(0);') },
    },
};
