// Access to the Custom Elements Manifest of every component package the site depends on: @pdxui/ui's
// (generated by its gen-manifest script) and @pdxui/router's (hand-written), read at build time by
// component-manifests-plugin.ts. The single source for the index and the component pages.

import packages from 'virtual:pdx-component-manifests';

export interface CemMember { name: string; type?: { text: string }; default?: string; description?: string; attribute?: string; }
export interface CemEvent { name: string; type?: { text: string }; description?: string; }
export interface CemNamed { name: string; description?: string; default?: string; }
export interface CemDecl {
    tagName: string;
    /** The package that ships it — `@pdxui/ui`, `@pdxui/router`. Set by this reader, not the manifest. */
    package: string;
    category: string;
    order: number;
    summary?: string;
    description?: string;
    attributes?: CemMember[];
    events?: CemEvent[];
    slots?: CemNamed[];
    cssProperties?: CemNamed[];
    members?: CemMember[];
}

// The manifest is generated, so its entries are trusted — but "trusted" has to mean something, and
// a cast would say only that it compiles. It does not even do that: the JSON's declared element
// type is `Record<string, unknown>`, which does not overlap `CemDecl`.
//
// A predicate instead of an assertion: a declaration that lost `tagName`, `category` or `order`
// stops being one, and the count check turns that from a page quietly missing into a build that
// says which generator drifted.
function isCemDecl(d: unknown): d is Omit<CemDecl, 'package'> {
    if (!d || typeof d !== 'object') return false;
    const c = d as Partial<CemDecl>;
    return typeof c.tagName === 'string' && typeof c.category === 'string' && typeof c.order === 'number';
}

const decls: CemDecl[] = [];
for (const { package: name, manifest } of packages) {
    const rawDecls: unknown[] = manifest.modules.map(m => m.declarations[0]).filter(Boolean);
    const own = rawDecls.filter(isCemDecl);
    if (own.length !== rawDecls.length) {
        throw new Error(
            `${name}: ${rawDecls.length - own.length} of ${rawDecls.length} manifest declarations `
            + 'are missing tagName, category or order — the manifest and this reader disagree.',
        );
    }
    for (const d of own) decls.push({ ...d, package: name });
}

/** Every component, in the barrel's order: the library's, then the other packages' (their `order` follows it). */
export function allComponents(): CemDecl[] {
    return [...decls].sort((a, b) => a.order - b.order);
}

/** One component by tag. Takes either the short name ("button") or the full tag ("pdx-button"). */
export function getComponent(tag: string): CemDecl | undefined {
    const full = tag && !tag.startsWith('pdx-') ? 'pdx-' + tag : tag;
    return decls.find(d => d.tagName === full || d.tagName === tag);
}

/** Components grouped by category (in order of first appearance). */
export function byCategory(): { category: string; items: CemDecl[] }[] {
    const order: string[] = [];
    const map: Record<string, CemDecl[]> = {};
    for (const d of allComponents()) {
        if (!map[d.category]) { map[d.category] = []; order.push(d.category); }
        map[d.category].push(d);
    }
    return order.map(c => ({ category: c, items: map[c] }));
}
