// Curated one-line summaries for the component index — the manifest carries almost none.
// Keyed by tag. Used as a fallback when the CEM has no summary/description.

export const summaries: Record<string, string> = {
    // ── Atoms ──────────────────────────────────────────────
    'pdx-button': 'Clickable action — 9 variants, sizes, loading and icons.',
    'pdx-button-group': 'Joined buttons that read as one control.',
    'pdx-icon': 'Crisp SVG icons from a shared set.',
    'pdx-input': 'Text field with sizes, states and addons.',
    'pdx-textarea': 'Multi-line text input that can auto-grow.',
    'pdx-checkbox': 'On/off box with an indeterminate state.',
    'pdx-radio': 'Pick a single option from a set.',
    'pdx-switch': 'Toggle a setting on or off.',
    'pdx-badge': 'A small count or status dot on anything.',
    'pdx-chip': 'Compact, optionally removable tag.',
    'pdx-avatar': 'User image or initials, any size.',
    'pdx-avatar-group': 'Stacked avatars with an overflow count.',
    'pdx-divider': 'A plain or labeled separating line.',
    'pdx-kbd': 'Render keyboard keys and shortcuts.',
    'pdx-label': 'A form label tied to its control.',
    'pdx-progress': 'Linear progress, determinate or not.',
    'pdx-spinner': 'A lightweight loading indicator.',

    // ── Forms & specialized inputs ─────────────────────────
    'pdx-slider': 'Pick a number by dragging.',
    'pdx-rating': 'Star rating with halves and tooltips.',
    'pdx-segmented': 'A compact set of exclusive options.',
    'pdx-toggle': 'A pressable on/off button.',
    'pdx-toggle-group': 'Exclusive or multi-select set of toggles.',
    'pdx-number-input': 'Numeric field with steppers and formatting.',
    'pdx-masked-input': 'Input that enforces a fixed format.',
    'pdx-password-input': 'Password field with reveal and strength.',
    'pdx-search-input': 'Search box with clear and shortcuts.',
    'pdx-otp-input': 'One-time-code entry boxes.',
    'pdx-pin-input': 'Segmented PIN entry.',
    'pdx-tag-input': 'Type to add removable tags.',
    'pdx-time-picker': 'Set hours and minutes.',
    'pdx-date-picker': 'Pick a date from a calendar.',
    'pdx-calendar': 'A month calendar surface.',
    'pdx-color-picker': 'Choose a color visually.',
    'pdx-file-upload': 'Drag-and-drop or browse to upload.',
    'pdx-cascader': 'Drill through nested options.',
    'pdx-tree-select': 'Select from a tree of options.',
    'pdx-transfer': 'Move items between two lists.',
    'pdx-mention': 'Type @ to mention people.',
    'pdx-inline-edit': 'Click text to edit it in place.',
    'pdx-checkbox-group': 'A managed set of checkboxes.',
    'pdx-radio-group': 'A managed set of radios.',
    'pdx-input-group': 'Inputs joined with addons and buttons.',
    'pdx-form': 'Schema-driven form with validation.',
    'pdx-form-field': 'Label, control, hint and error in one.',
    'pdx-field-group': 'Group related fields together.',
    'pdx-field-list': 'Repeatable arrays of fields.',
    'pdx-fieldset': 'A bordered, titled group of fields.',
    'pdx-form-section': 'A titled section within a form.',
    'pdx-form-actions': 'The submit/cancel action bar.',
    'pdx-form-template': 'Render a whole form from a layout.',
    'pdx-statistic': 'A big number with label and trend.',
    'pdx-relative-time': 'Auto-updating “3 days ago”.',
    'pdx-list': 'Data-driven list with custom rows.',
    'pdx-description-list': 'Key/value pairs, neatly aligned.',
    'pdx-timeline': 'A vertical sequence of events.',
    'pdx-pagination': 'Page through long results.',
    'pdx-infinite-scroll': 'Load more as you scroll.',
    'pdx-scroll-area': 'A styled, custom scrollbar region.',
    'pdx-scroll-spy': 'Highlight the section you’re viewing.',
    'pdx-carousel': 'A swipeable slideshow.',
    'pdx-masonry': 'A staggered, Pinterest-style grid.',
    'pdx-image': 'Lazy, responsive image with placeholder.',
    'pdx-aspect-ratio': 'Lock content to a fixed ratio.',
    'pdx-empty-state': 'A friendly “nothing here yet”.',
    'pdx-affix': 'Pin an element while scrolling.',
    // Not "sidebar": there is no `sidebar` region. The four names are header/navbar/aside/footer,
    // and anything without a data-region becomes the main area. Saying "sidebar" here sends a
    // reader looking for an attribute that does not exist.
    'pdx-app-layout': 'App shell: header, left/right sidebars, footer, and everything else as the main area.',
    'pdx-navbar': 'A top navigation bar.',
    'pdx-sidebar': 'Collapsible side navigation.',
    'pdx-bottom-nav': 'Mobile bottom navigation.',
    'pdx-nav-menu': 'A multi-level navigation menu.',
    'pdx-menubar': 'A desktop-style menu bar.',
    'pdx-menu': 'A list of actions.',
    'pdx-dropdown-menu': 'A button that opens an action menu.',
    'pdx-context-menu': 'A right-click menu.',
    'pdx-breadcrumb': 'Show the path to here.',
    'pdx-page-header': 'Breadcrumb, title and page actions.',
    'pdx-toolbar': 'A row of grouped actions.',
    'pdx-split-button': 'A primary action plus a menu.',
    'pdx-fab': 'A floating action button.',
    'pdx-splitter': 'Resizable panes.',
    'pdx-col': 'A responsive grid column.',
    'pdx-row': 'A responsive grid row.',
    'pdx-wizard': 'A guided multi-step flow.',
    'pdx-block-ui': 'Block a region while it’s busy.',

    // ── Overlay & containers ───────────────────────────────
    'pdx-card': 'A surface for grouped content.',
    'pdx-accordion': 'Expandable, collapsible sections.',
    'pdx-tabs': 'Switch between panels.',
    'pdx-dialog': 'A modal window with focus trap.',
    'pdx-alert-dialog': 'A confirm / cancel modal.',
    'pdx-drawer': 'A panel that slides in from an edge.',
    'pdx-bottom-sheet': 'A panel that rises from the bottom.',
    'pdx-popover': 'Floating content anchored to a trigger.',
    'pdx-tooltip': 'A hint on hover or focus.',
    'pdx-toast': 'Transient, stacked notifications.',
    'pdx-banner': 'A persistent inline message.',
    'pdx-command': 'A ⌘K command palette.',

    // ── Data-bound ─────────────────────────────────────────
    'pdx-data-grid': 'Sortable, filterable, virtual data table.',
    'pdx-data-source': 'One reactive source of rows for grids, lists, selects, charts and forms.',
    'pdx-select': 'A searchable dropdown select.',
    'pdx-autocomplete': 'Suggestions as you type.',
    'pdx-auto-form': 'A form generated from a schema.',
    'pdx-chart': 'Charts from your data.',
    'pdx-sparkline': 'A tiny inline trend chart.',
    'pdx-filter-builder': 'Build complex filters visually.',
    'pdx-rich-text': 'A WYSIWYG editor.',
    'pdx-entity-grid': 'A CRUD grid: create, edit, delete, bulk.',
    'pdx-edit-drawer': 'A drawer holding a schema-driven form.',
    'pdx-bulk-actions': 'An action bar for the current selection.',
    'pdx-relation-picker': 'Pick existing rows for a relation.',
    'pdx-json-editor': 'Edit nested JSON through a schema.',

    // ── Infrastructure ─────────────────────────────────────
    'pdx-error-boundary': 'Catch and recover from render errors.',
    'pdx-provide': 'Provide context to a subtree.',
    'pdx-overlay-outlet': 'A mount point for overlays.',
};
