// The inline render path must render a slot, and import what it calls.
//
// A component that projects through a slot depends on two things in the same place.
//
// 1. `generateInlineNodes`'s `walk` needs a case for `slot-template`: without one, a
//    `default: break;` drops a `<slot name="item" let:label>` written inside a component's tag from
//    the emitted module, silently, which is what a default branch over a node-type union buys you.
//
// 2. `html` stays in the imports when the inline path runs. "Inline codegen doesn't use html``" is
//    true of the render, false of the module: a scoped slot is hoisted into its own function,
//    emitted OUTSIDE the render precisely because it cannot be nested in a template literal, and
//    that function is generated by the template path. A module that calls `html` without importing
//    it throws:
//
//        [pdx] Unhandled effect error: ReferenceError: html is not defined
//            at Object.b [as renderItemContent] …
//
// The assertions below are the two halves plus the control that keeps the second honest: a
// component with no slot must NOT carry an import it never calls, or "inline" would quietly start
// shipping the template runtime.

import { describe, it, expect } from 'vitest';
import { compile } from '../src/plugin';

const SLOTTED = `<template>
  <pdx-select label="Team member" :options="people" labelField="name" valueField="id">
    <slot name="item" let:label let:raw>
      <span class="who">{{ label }}</span>
    </slot>
  </pdx-select>
</template>

<script setup>
const people = [{ id: 1, name: 'Ada' }];
</script>`;

const PLAIN = `<template><p :title="t">{{ t }}</p></template>
<script setup>
@prop t: string = '';
</script>`;

const emitted = (source: string, inlineBindings: boolean): string =>
    compile(source, 'list.pdx', [], undefined, { production: true, inlineBindings }).code;

/** The names the module imports from `@pdxui/core`. */
function importedNames(code: string): string[] {
    const m = /import\s*\{([^}]*)\}\s*from\s*'@pdxui\/core'/.exec(code);
    return m ? m[1].split(',').map(s => s.trim()).filter(Boolean) : [];
}

describe('a scoped slot survives the inline path', () => {
    it('the slot reaches the emitted module', () => {
        const code = emitted(SLOTTED, true);
        expect(code, 'the slot was dropped from the render').toContain("slotCarrier('item'");
        expect(importedNames(code), 'slotCarrier is called and not imported').toContain('slotCarrier');
    });

    it('its body is there too, not just the carrier', () => {
        // A carrier with an empty function renders nothing, and would satisfy the assertion above.
        expect(emitted(SLOTTED, true), 'the slot function has no body').toContain('who');
    });

    it('and it is attached to something, not created and forgotten', () => {
        expect(emitted(SLOTTED, true), 'the carrier was built and never appended')
            .toMatch(/appendChild\(slotCarrier\('item'/);
    });

    it('control — the template path renders the same slot', () => {
        // Without this, a change that stopped BOTH paths emitting slots would pass the tests above.
        expect(emitted(SLOTTED, false)).toContain("slotCarrier('item'");
    });
});

describe('the module imports what it calls', () => {
    it('html, because the hoisted slot function uses it', () => {
        const code = emitted(SLOTTED, true);
        // Guard the premise: if the hoisted slot ever stops using html``, rewrite this rather than
        // let it pass for a new reason.
        expect(code, 'the hoisted slot no longer uses html`` — re-read this test').toMatch(/html`/);
        expect(importedNames(code), 'the module calls html and does not import it').toContain('html');
    });

    it('and still drops html when nothing uses it', () => {
        // The delete was not wrong, only unconditional. A component with no slot must not carry an
        // import it never calls, or the inline path would start shipping the template runtime.
        const code = emitted(PLAIN, true);
        expect(code).not.toMatch(/html`/);
        expect(importedNames(code), 'an unused html import came back').not.toContain('html');
    });
});

describe('and the emitted module parses', () => {
    it('with a slot in it', () => {
        // `new Function` is a parser that is already here. The import lines are stripped because an
        // import statement is illegal in a function body; the body is never called, only compiled.
        const body = emitted(SLOTTED, true).replace(/^\s*import\b.*$/gm, '');
        expect(() => new Function(body)).not.toThrow();
    });
});
