// How often does the signal rewriter actually give up?
//
// PDX_REWRITE_FALLBACK fires when the rewriter meets a fragment it cannot parse, or edits that
// overlap, and skips the rewrite — leaving generated code that reads a signal without calling it.
// Is this tidiness, or does it fire on ordinary files?
//
// Measured over every .pdx this repository ships: it fires on NONE of them. That is worth keeping
// rather than noting once, for two reasons. It is the control on the diagnostic — one
// that fired on ordinary code would be noise nobody reads — and it is the guard on the rewriter: the
// day a construct someone writes starts defeating it, this names the file instead of shipping a
// component whose signal quietly stopped being reactive.
//
// Asserted on the returned `warnings`, which is the diagnostic's channel, not on a console spy.

import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { compile } from '../src/plugin';

const ROOT = join(__dirname, '..', '..', '..');
const SKIP = new Set(['node_modules', 'dist', '.git', 'coverage', 'test-results', 'playwright-report']);
// The site's copies of the showcase pages: generated by its build, git-ignored, and the same files the
// corpus already reads under compiler/demo/showcase-new. Read, they doubled the corpus wherever the site
// had been built — the CI coverage job builds it first — and left it at half on a fresh clone (#87).
const GENERATED = new Set([join(ROOT, 'packages', 'site', 'src', 'demos')]);

function pdxFiles(dir: string, out: string[] = []): string[] {
    let entries: string[];
    try { entries = readdirSync(dir); } catch { return out; }
    for (const name of entries) {
        if (SKIP.has(name)) continue;
        const p = join(dir, name);
        if (GENERATED.has(p)) continue;
        let st;
        try { st = statSync(p); } catch { continue; }
        if (st.isDirectory()) pdxFiles(p, out);
        else if (name.endsWith('.pdx')) out.push(p);
    }
    return out;
}

const FILES = pdxFiles(join(ROOT, 'packages')).concat(pdxFiles(join(ROOT, 'templates')));

/** The rewriter's fallbacks for one source, as `PDX_REWRITE_FALLBACK` messages. Throws if it does not compile. */
function fallbacksOf(source: string, file: string): string[] {
    return compile(source, file).warnings
        .filter((w) => w.code === 'PDX_REWRITE_FALLBACK')
        .map((w) => w.message.slice(0, 160));
}

describe('every .pdx in the repository', () => {
    it('is a corpus worth calling one', () => {
        // Without this the per-file tests below would pass on an empty list.
        expect(FILES.length).toBeGreaterThan(300);
    });

    // One test per file, not one test for the corpus (#87). As a single test, its time grew with every
    // .pdx added and with the runner's load: 16 s in the coverage job on main, then past its 30 s bound
    // on a busy runner. Each file is milliseconds; a failure names it.
    it.each(FILES.map((file) => [file.slice(ROOT.length + 1).replace(/\\/g, '/'), file]))(
        '%s compiles, and does not defeat the signal rewriter',
        (_rel, file) => {
            expect(
                fallbacksOf(readFileSync(file, 'utf8'), file),
                'the rewriter skipped these — the generated code reads a signal without calling it',
            ).toEqual([]);
        },
    );

    it('the control: the check sees a fallback when there is one', () => {
        // No file in the corpus defeats the rewriter, so the per-file assertion never sees a fallback
        // there. This shows it would: a reactive read the rewriter cannot parse. If this ever stops
        // producing one, find another construct that does, rather than drop the control.
        const broken = '<template><p>{{ n }}</p></template>\n<script setup>\nlet n = $signal(0);\nconst f = () => { n = ( ; };\n</script>';
        expect(fallbacksOf(broken, 'control.pdx').length).toBeGreaterThan(0);
    });
});
