// The dev/prod seam: a production build runs the generated router.
//
// The switch-based router is at parity with the interpreted one, but parity is worth nothing if
// nothing imports it: an `outlet.ts` importing `./runtime` unconditionally would make every
// `@guard` in a production build evaluated by the dev regex router.
//
// The seam is ONE file — `packages/router/src/active.ts` — and it is swapped by CONTENT rather than
// by a fork through the code: in dev it is a real module re-exporting `./runtime`, and in a
// production build the plugin's `load` hook answers for it with the generated module. Every other
// file in the package, and every component that imports `@pdxui/router`, therefore talks to
// exactly one router at a time. That is what keeps `p2-plus.test.ts`'s "no component imports
// virtual:pdx-router" assertion meaningful instead of protecting a split brain it cannot see.

import { describe, it, expect } from 'vitest';
import { pdx } from '../src/plugin';
import { generateOptimizedRouter } from '../src/plugin-utils';

type Hooks = {
    config: (c: object, e: { command: string }) => void;
    load: (id: string) => string | undefined;
};

/** The plugin with its mode decided, and the two hooks this file drives. */
function pluginIn(command: 'build' | 'serve'): Hooks {
    const plugin = pdx({ autoAlias: false }) as unknown as Hooks;
    plugin.config({}, { command });
    return plugin;
}

// A POSIX id, which is what Vite hands `load` even on Windows.
const SEAM = '/w/packages/router/src/active.ts';
const INSTALLED = '/w/node_modules/@pdxui/router/src/active.ts';

describe('the seam', () => {
    it('answers for the router package seam in a production build', () => {
        const out = pluginIn('build').load(SEAM);

        expect(out, 'the seam was left as the interpreted router in a production build').toBeTruthy();
        expect(out).toContain('Generated by @pdxui/compiler');
    });

    it('answers for it when the package is installed from node_modules too', () => {
        // The monorepo is not the only shape this ships in, and a seam that only works in the
        // monorepo is a seam that only works for us.
        expect(pluginIn('build').load(INSTALLED)).toBeTruthy();
    });

    it('leaves the seam alone in dev', () => {
        // The control. Swapping in both modes would make the "dual" in dual mode a lie in the other
        // direction, and dev would lose HMR on the router it actually runs.
        expect(pluginIn('serve').load(SEAM)).toBeUndefined();
    });

    it('does not answer for any other file in the package', () => {
        const build = pluginIn('build');

        expect(build.load('/w/packages/router/src/runtime.ts')).toBeUndefined();
        expect(build.load('/w/packages/router/src/outlet.ts')).toBeUndefined();
        expect(build.load('/w/packages/router/src/index.ts')).toBeUndefined();
        // A file merely NAMED active.ts elsewhere is not this package's seam.
        expect(build.load('/w/packages/site/src/active.ts')).toBeUndefined();
    });

    it('still serves the virtual module under its own id', () => {
        // The seam is an additional door to the same module, not a replacement for the one the
        // parity suite and `import 'virtual:pdx-router'` already use.
        expect(pluginIn('build').load('\0virtual:pdx-router')).toBeTruthy();
    });
});

describe('what the seam has to export to be a drop-in', () => {
    // The runtime router's public surface, as `packages/router/src/active.ts` re-exports it. Every
    // name here is imported somewhere in the package or re-exported from its index, so a missing one
    // is a build that fails on `import { … } from '@pdxui/router'` — in production only, which
    // is the worst place to find out.
    const SURFACE = [
        'createRouter', 'destroyRouter', 'navigate',
        'currentPath', 'currentParams', 'currentQuery', 'currentSearch', 'currentMeta',
        'currentState', 'currentLoaderData', 'currentLoaderState', 'currentRoute', 'currentNavError',
        'onBeforeNavigate', 'onAfterNavigate', 'registerGuardChecker', 'setQuery', 'setQueryParam',
    ];

    it('exports every name the interpreted router does', () => {
        const code = generateOptimizedRouter([{ path: '/', file: 'home.pdx', tag: 'pdx-home' }]);
        const missing = SURFACE.filter(n => !new RegExp(`export (?:function|const) ${n}\\b`).test(code));

        expect(missing, 'these are exported by ./runtime and not by the generated module').toEqual([]);
    });

    it('exports them even for a project with no @page at all', () => {
        // It used to answer a route-less project with `export const routes = []` and nothing else.
        // Harmless while nothing imported it; at the seam it is a production build that fails on
        // every other import — and an app can legitimately have no @page yet.
        const code = generateOptimizedRouter([]);
        const missing = SURFACE.filter(n => !new RegExp(`export (?:function|const) ${n}\\b`).test(code));

        expect(missing, 'a route-less project got a stub instead of a router').toEqual([]);
        expect(code).toContain('const _loaderModules = {};');
    });

    it('createRouter applies the options it is given and re-resolves', () => {
        // The generated module resolves location.pathname when it is IMPORTED, which is before the
        // outlet has registered the guard checker or the pages have registered their loaders.
        // createRouter is the outlet saying "now" — without a re-resolution the first page of every
        // production app would be the one decided before anything was ready.
        const code = generateOptimizedRouter([{ path: '/', file: 'home.pdx', tag: 'pdx-home' }]);

        expect(code).toMatch(/export function createRouter\(routes, options\)/);
        expect(code).toContain('configureRouter(options)');
        expect(code, 'createRouter did not re-resolve the current location').toMatch(/createRouter[\s\S]{0,400}_handleNav\(/);
    });
});
