// DTS Generator — produces .pdx.d.ts files for IntelliSense.
// Generates: Props, Events, Slots, Fetches, Forms, Stores, SearchParams, HTMLElementTagNameMap.

import type { PropInfo, EventInfo, SlotInfo, FetchDecl, StoreDecl } from './script-analyzer';
import type { SearchParamDecl } from './script-analyzer-types';

export interface DtsInput {
    tag: string;
    props: PropInfo[];
    events: EventInfo[];
    slots: SlotInfo[];
    /** @fetch declarations — generates typed resource accessors. */
    fetches?: FetchDecl[];
    /** @store declaration — generates useXxx() hook type. */
    store?: StoreDecl;
    /** @search params — generates SearchParams interface. */
    searchParams?: SearchParamDecl[];
    /** @form declarations — generates form value types. */
    forms?: { name: string; schemaType?: string }[];
}

/**
 * Generate a .d.ts file content for a .pdx component.
 */
export function generateDts(input: DtsInput): string {
    const pascalTag = toPascalCase(input.tag);
    const lines: string[] = [];

    lines.push('// Auto-generated by @pdxui/compiler — do not edit');
    lines.push('');

    // Props interface
    lines.push(`export interface ${pascalTag}Props {`);
    for (const p of input.props) {
        lines.push(`  ${p.name}?: ${p.tsType};`);
    }
    lines.push('}');
    lines.push('');

    // Events interface
    if (input.events.length > 0) {
        lines.push(`export interface ${pascalTag}Events {`);
        for (const e of input.events) {
            lines.push(`  ${e.name}: ${e.payloadType};`);
        }
        lines.push('}');
        lines.push('');
    }

    // Slots interface (with scope type if declared)
    if (input.slots.length > 0) {
        lines.push(`export interface ${pascalTag}Slots {`);
        for (const s of input.slots) {
            lines.push(`  ${s.name}: ${s.scopeType ?? '{}'};`);
        }
        lines.push('}');
        lines.push('');
    }

    // Fetch resource types
    if (input.fetches?.length) {
        for (const f of input.fetches) {
            const typeName = f.type ?? 'unknown';
            lines.push(`export type ${capitalize(f.name)}Resource = ${typeName};`);
        }
        lines.push('');
    }

    // Search params interface
    if (input.searchParams?.length) {
        lines.push(`export interface ${pascalTag}SearchParams {`);
        for (const p of input.searchParams) {
            const opt = p.optional ? '?' : '';
            lines.push(`  ${p.name}${opt}: ${p.type};`);
        }
        lines.push('}');
        lines.push('');
    }

    // Store hook type
    if (input.store) {
        const hookName = `use${capitalize(input.store.name)}`;
        lines.push(`export declare function ${hookName}(): Record<string, unknown>;`);
        lines.push('');
    }

    // Form value types
    if (input.forms?.length) {
        for (const f of input.forms) {
            if (f.schemaType) {
                lines.push(`export type ${capitalize(f.name)}FormValues = ${f.schemaType};`);
            }
        }
        if (input.forms.some(f => f.schemaType)) lines.push('');
    }

    // HTMLElementTagNameMap augmentation
    lines.push('declare global {');
    lines.push('  interface HTMLElementTagNameMap {');
    lines.push(`    '${input.tag}': HTMLElement & ${pascalTag}Props;`);
    lines.push('  }');
    lines.push('}');
    lines.push('');

    return lines.join('\n');
}

function toPascalCase(kebab: string): string {
    return kebab.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('');
}

function capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
}
