// @pdxui/router — the public surface, over whichever router the build is running.
//
// PDX has two routers:
//
// - DEV runs the interpreted one (`./runtime`): a generic regex matcher that needs no build step,
//   so `pdx dev` is Vite and HMR and nothing else.
// - A PRODUCTION BUILD runs the generated one — a switch with no regex and no loop, compiled by
//   @pdxui/compiler from the project's own `@page` declarations.
//
// Everything below comes through `./active`, which is the seam and the only place either
// implementation is named: in a production build the compiler's `load` hook answers for that file
// with the generated module. One router per build, chosen in one place, so a component importing
// from here can never read one router while the app navigates with the other.
//
// That the two are interchangeable is not an assumption: `packages/router/tests/parity.test.ts`
// runs one table of behaviours against both, and no row of it is owed to an open issue.

export {
    createRouter, destroyRouter, navigate,
    currentPath, currentParams, currentQuery, currentSearch, currentMeta, currentState,
    currentLoaderData, currentLoaderState, loaderData, loaderState, currentRoute, currentNavError,
    onBeforeNavigate, onAfterNavigate,
    registerGuardChecker, setQuery, setQueryParam,
} from './active';
export type { RouteConfig, ResolvedRoute, RouterOptions, NavigationHop } from './active';

// Compile-time router types. The optimized ad-hoc router is generated by
// @pdxui/compiler (virtual:pdx-router); these type aliases keep public imports
// type-checking, but no runtime generator ships from this package.
/** A route entry as collected from a @page declaration at build time. */
export interface RouteEntry {
    path: string;
    file: string;
    params: { name: string; type: string; segmentIndex: number }[];
    guard?: string;
    /**
     * The @loader function — not its name: RouteConfig types it `() => Promise<unknown>`, and the
     * compiler hoists the declaration to module scope and registers the reference, so this is a
     * function everywhere it matters.
     */
    loader?: () => Promise<unknown>;
    search?: string;
    prefetch?: string;
    transition?: string;
    layout?: string;
    meta?: Record<string, unknown>;
    outlets?: { name: string; tag: string }[];
    aliases?: string[];
    redirect?: string;
}
/** Result of generating an optimized router from route entries. */
export interface GeneratedRouter {
    code: string;
    dts: string;
    speculationRules?: string;
    entries: RouteEntry[];
}

// Router outlet — keep-alive page rendering
export { PdxRouterOutlet, routeParams } from './outlet';

// Navigation link — SPA-aware <a> with prefetch + active class
export { PdxLink } from './link';

// Start a route's chunk before anything renders it: an app that holds its outlet (for the route's
// strings, say) starts the chunk alongside, rather than after.
export { prefetchRoute } from './prefetch';
