/**
 * MANIFEST — pdx-accordion
 *
 * Mathematical contracts transcribed FAITHFULLY from contracts/universal.ts (the component:
 * 'accordion' block). The scenario markup comes from the component-contracts.html monolith
 * (scenario accordion-basic).
 * Note: accordion-basic is CSS-only (<details class="pdx-accordion">, not a custom element); the
 * custom element is exercised by accordion-two-instances, which is why imports carries
 * '@pdxui/ui/accordion'.
 */
import type { ComponentManifest } from './_types';

export const accordion: ComponentManifest = {
    name: 'accordion',
    tag: 'pdx-accordion',
    tier: '2B',
    status: 'wip',
    imports: ['@pdxui/ui/accordion'],

    // ── Scenarios (the markup comes from the component-contracts.html monolith) ──
    scenarios: [
        {
            // The custom element's first scenario: two instances on one page. Ids generated by
            // index, `pdx-acc-content-${i}`, would be the same in both, and axe sees that
            // (duplicate-id-aria).
            id: 'accordion-two-instances',
            title: 'Accordion — two instances on one page',
            html: `
                <pdx-accordion data-test="acc-a">
                    <div data-accordion-item data-open>
                        <button data-accordion-trigger>Shipping</button>
                        <div data-accordion-content>Orders ship within two days.</div>
                    </div>
                    <div data-accordion-item>
                        <button data-accordion-trigger>Returns</button>
                        <div data-accordion-content>Returns are free for thirty days.</div>
                    </div>
                </pdx-accordion>
                <pdx-accordion data-test="acc-b">
                    <div data-accordion-item data-open>
                        <button data-accordion-trigger>Billing</button>
                        <div data-accordion-content>Invoices are sent monthly.</div>
                    </div>
                    <div data-accordion-item>
                        <button data-accordion-trigger>Support</button>
                        <div data-accordion-content>Support answers within a day.</div>
                    </div>
                </pdx-accordion>`,
        },
        {
            // A disabled item: its trigger stays focusable, as the APG accordion keeps a disabled
            // header discoverable, and says it is disabled with aria-disabled, so the arrow keys do
            // not land on what reads as an ordinary button. The native <details> after it gives the
            // Tab check a target outside the accordion.
            id: 'accordion-disabled-item',
            title: 'Accordion — a disabled item',
            html: `
                <pdx-accordion mode="multiple">
                    <div data-accordion-item>
                        <button data-accordion-trigger data-test="acc-security">Security</button>
                        <div data-accordion-content>Two-factor authentication is on.</div>
                    </div>
                    <div data-accordion-item data-disabled>
                        <button data-accordion-trigger data-test="acc-admin">Admin (requires permissions)</button>
                        <div data-accordion-content>Admin settings.</div>
                    </div>
                    <div data-accordion-item>
                        <button data-accordion-trigger data-test="acc-billing">Billing</button>
                        <div data-accordion-content>Invoices are sent monthly.</div>
                    </div>
                </pdx-accordion>
                <details class="pdx-accordion" data-test="accordion-closed">
                    <summary>Closed Accordion</summary>
                    <div>Content of closed accordion.</div>
                </details>`,
        },
        {
            id: 'accordion-basic',
            title: 'Accordion — Basic',
            html: `
                <details class="pdx-accordion" data-test="accordion-closed">
                    <summary>Closed Accordion</summary>
                    <div>Content of closed accordion.</div>
                </details>
                <details class="pdx-accordion" data-test="accordion-open" open>
                    <summary>Open Accordion</summary>
                    <div>Content of open accordion.</div>
                </details>`,
        },
    ],

    // ── Dim. 1: the mathematical contract (transcribed from universal.ts) ──
    contracts: {
        scenarios: {
            'accordion-basic': {
                standalone: [
                    {
                        selector: '[data-test="accordion-closed"] summary',
                        description: 'accordion summary has cursor pointer',
                        cursor: { op: 'is', value: 'pointer' },
                    },
                    {
                        selector: '[data-test="accordion-open"]',
                        description: 'open accordion has visible content',
                        height: { op: '>=', value: 40 },
                    },
                ],
            },
        },
    },

    // ── Dim. 2: axe-core ──
    a11y: {
        scenarios: ['accordion-basic', 'accordion-two-instances', 'accordion-disabled-item'],
    },

    // ── Dim. 3: style isolation ──
    isolation: {
        scenario: 'accordion-basic',
        targets: [
            { selector: '[data-test="accordion-open"]', tolerancePx: 6 },
        ],
    },

    // ── Dim. 4: keyboard (WAI-ARIA) ──
    keyboard: {
        scenario: 'accordion-disabled-item',
        steps: [
            { key: 'Tab', expectFocus: '[data-test="acc-security"]' },
            // The arrow keys reach the disabled header, which announces itself…
            { key: 'ArrowDown', expectFocus: '[data-test="acc-admin"]',
              expectAttr: { selector: '[data-test="acc-admin"]', name: 'aria-disabled', value: 'true' } },
            // …and does not open.
            { key: 'Enter', expectAttr: { selector: '[data-test="acc-admin"]', name: 'aria-expanded', value: 'false' } },
            { key: 'ArrowDown', expectFocus: '[data-test="acc-billing"]' },
            // One tab stop for the accordion: Tab leaves it, for the native <details> after it.
            { key: 'Tab', expectFocus: '[data-test="accordion-closed"] summary' },
        ],
    },

    // ── Dim. 5: visual regression (Docker) ──
    visual: {
        scenarios: ['accordion-basic'],
    },
};

export default accordion;
