import type { Plugin } from 'vite';
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { join, relative, isAbsolute } from 'node:path';

/**
 * The last mile: a theme authored in the UI becomes a real theme in the repo.
 *
 * Without this, "create a theme" ends at a download and the human has to place the file and
 * register it by hand — which is exactly the boilerplate the framework is supposed to remove.
 *
 * Blast radius is deliberately one directory. A save writes `themes/custom/<name>.css` and,
 * if needed, appends one `@import` to `themes/custom/_custom.css`. The shipped themes,
 * `pragmatic-design.css` and `package.json` are never touched: `_custom.css` is imported once
 * (reviewed by a human, in a commit), so a bad save cannot break the design package.
 *
 * Dev-server only. It writes to the working tree, so it exists solely while `pdx builder`
 * runs; nothing here ships.
 */

/** Theme names are used in a CSS attribute selector and as a filename. Keep them boring. */
const NAME_RE = /^[a-z][a-z0-9-]{1,39}$/;

/**
 * Moves the custom-theme directory away from `packages/design/src/themes/custom/`. The builder's
 * e2e suite points it at a temp directory: the design suite serves the working tree in the same
 * `pnpm test`, and a theme file the builder's cleanup deletes there crashes its server.
 * Unset, a save lands where a human wants it — in the repo, to be committed.
 */
export const CUSTOM_THEMES_ENV = 'PDX_BUILDER_CUSTOM_THEMES_DIR';

/** The inputs a theme came from, so the file can say how to rebuild itself. */
export interface ThemeOrigin {
    brand?: string;
    language?: string;
    accent?: string;
    focus?: string;
    neutral?: string;
    density?: string;
    radius?: string;
}

export interface SaveResult {
    ok: boolean;
    error?: string;
    /** Paths written, relative to the repo root. */
    written?: string[];
    /** True when an existing custom theme was replaced. */
    replaced?: boolean;
}

export function themeSavePlugin(repoRoot: string): Plugin {
    const themesDir = join(repoRoot, 'packages/design/src/themes');
    const customDir = process.env[CUSTOM_THEMES_ENV] || join(themesDir, 'custom');
    const aggregator = join(customDir, '_custom.css');

    /** A written path as the result reports it: relative to the repo when inside it. */
    const shown = (file: string): string => {
        const rel = relative(repoRoot, file);
        return rel.startsWith('..') || isAbsolute(rel) ? file : rel.split('\\').join('/');
    };

    const shippedThemes = (): string[] =>
        existsSync(themesDir)
            ? readdirSync(themesDir).filter(f => f.endsWith('.css')).map(f => f.slice(0, -4)).sort()
            : [];

    const customThemes = (): string[] =>
        existsSync(customDir)
            ? readdirSync(customDir)
                .filter(f => f.endsWith('.css') && !f.startsWith('_'))
                .map(f => f.slice(0, -4)).sort()
            : [];

    /**
     * The header must be RUNNABLE: the placeholders `--brand <colour> --language <archetype>`
     * are filled with the values the builder knows — a hint that cannot be pasted is worse than
     * none, because it looks like one that can.
     */
    function regenerateHint(name: string, origin?: ThemeOrigin): string {
        if (!origin?.brand) return `pdx theme ${name} --brand <colour> --language <archetype>`;
        const parts = [`pdx theme ${name}`, `--brand "${origin.brand}"`];
        if (origin.language) parts.push(`--language ${origin.language}`);
        if (origin.accent) parts.push(`--accent "${origin.accent}"`);
        if (origin.focus) parts.push(`--focus "${origin.focus}"`);
        if (origin.neutral) parts.push(`--neutral ${origin.neutral}`);
        if (origin.density && origin.density !== 'normal') parts.push(`--density ${origin.density}`);
        if (origin.radius) parts.push(`--radius ${origin.radius}`);
        return parts.join(' ');
    }

    function save(name: string, css: string, origin?: ThemeOrigin): SaveResult {
        if (!NAME_RE.test(name)) {
            return { ok: false, error: `Invalid theme name "${name}". Use lowercase letters, digits and dashes, starting with a letter.` };
        }
        if (shippedThemes().includes(name)) {
            return { ok: false, error: `"${name}" is a shipped theme. Pick another name — saving never overwrites what ships.` };
        }
        if (!css.includes(`[pdx-theme="${name}"]`)) {
            return { ok: false, error: `The CSS does not define [pdx-theme="${name}"] — refusing to write a file that would do nothing.` };
        }

        if (!existsSync(customDir)) mkdirSync(customDir, { recursive: true });
        const file = join(customDir, `${name}.css`);
        const replaced = existsSync(file);
        const header = `/* GENERATED by the PDX Builder. Re-saving the same name overwrites this file.\n   Regenerate with: ${regenerateHint(name, origin)} */\n`;
        writeFileSync(file, header + css + '\n', 'utf8');

        const written = [shown(file)];

        // Append the import only when missing: saving twice must not duplicate it.
        const importLine = `@import "./${name}.css" layer(pdx.themes);`;
        const current = existsSync(aggregator) ? readFileSync(aggregator, 'utf8') : '';
        if (!current.includes(importLine)) {
            writeFileSync(aggregator, current.trimEnd() + '\n\n' + importLine + '\n', 'utf8');
            written.push(shown(aggregator));
        }

        return { ok: true, written, replaced };
    }

    return {
        name: 'pdx-builder-theme-save',
        apply: 'serve',
        configureServer(server) {
            server.middlewares.use('/__pdx/themes', (_req, res) => {
                res.setHeader('Content-Type', 'application/json');
                // A live directory listing: a cached copy is a wrong answer by definition,
                // and the one moment it is asked again is right after something changed.
                res.setHeader('Cache-Control', 'no-store');
                res.end(JSON.stringify({ shipped: shippedThemes(), custom: customThemes() }));
            });

            // A saved theme's CSS, read from wherever it was saved. Not by its path in the working
            // tree, which is only right while the directory is the default one.
            server.middlewares.use('/__pdx/custom-themes', (req, res) => {
                const file = (req.url ?? '').split('?')[0].replace(/^\//, '');
                // The name rule is also what keeps the path inside the directory.
                if (!file.endsWith('.css') || !NAME_RE.test(file.slice(0, -4)) || !existsSync(join(customDir, file))) {
                    res.statusCode = 404;
                    res.end('Not found');
                    return;
                }
                res.setHeader('Content-Type', 'text/css');
                res.setHeader('Cache-Control', 'no-store');
                res.end(readFileSync(join(customDir, file)));
            });

            server.middlewares.use('/__pdx/save-theme', (req, res) => {
                if (req.method !== 'POST') { res.statusCode = 405; res.end('POST only'); return; }
                let body = '';
                req.on('data', (c) => { body += c; });
                req.on('end', () => {
                    res.setHeader('Content-Type', 'application/json');
                    let result: SaveResult;
                    try {
                        const { name, css, origin } = JSON.parse(body) as { name?: string; css?: string; origin?: ThemeOrigin };
                        result = (!name || !css)
                            ? { ok: false, error: 'name and css are required' }
                            : save(name, css, origin);

                    } catch (err) {
                        result = { ok: false, error: String((err as Error)?.message ?? err) };
                    }
                    res.statusCode = result.ok ? 200 : 400;
                    res.end(JSON.stringify(result));
                });
            });
        },
    };
}
