/**
 * The last mile: a theme authored in the UI becomes a real theme in the repo.
 *
 * Export alone leaves the human with a download and a manual registration — the boilerplate
 * the framework exists to remove. These tests drive the actual button and then look at the
 * working tree, because "the UI said Saved" is not the claim being made.
 *
 * Under test the dev server writes to a directory of its own (CUSTOM_THEMES_DIR, handed to it by
 * the Playwright config), never to `packages/design/src/themes/custom/`: the design suite serves
 * that directory in the same `pnpm test`, and a theme file deleted under it crashes its server.
 * The cleanup below undoes the suite's own directory.
 */
import { test, expect, type Page } from '@playwright/test';
import { existsSync, readFileSync, readdirSync, writeFileSync, unlinkSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { CUSTOM_THEMES_DIR, CUSTOM_THEMES_ENV } from './custom-themes-dir';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const customDir = CUSTOM_THEMES_DIR;
const aggregator = resolve(customDir, '_custom.css');

const NAME = 'builder-test-theme';
const themeFile = resolve(customDir, `${NAME}.css`);

/** The working tree's custom-theme directory, as it is: every file and its content. */
const workingTreeCustom = resolve(repoRoot, 'packages/design/src/themes/custom');
function workingTreeSnapshot(): Record<string, string> {
    if (!existsSync(workingTreeCustom)) return {};
    return Object.fromEntries(readdirSync(workingTreeCustom).sort().map((f) => [f, readFileSync(resolve(workingTreeCustom, f), 'utf8')]));
}
const workingTreeBefore = workingTreeSnapshot();

test.use({ viewport: { width: 1600, height: 1000 } });

// These tests write to shared files, so they cannot run against each other: the cleanup of one
// would land in the middle of another. Serial within this file; no other spec saves a theme, so the
// rest of the suite stays parallel.
test.describe.configure({ mode: 'serial' });

// The aggregator first, the theme file second: in the other order `_custom.css` imports a file that
// no longer exists, and anything serving the directory in between answers — or crashes — on it.
function cleanup(): void {
    if (existsSync(aggregator)) {
        const kept = readFileSync(aggregator, 'utf8')
            .split('\n').filter(l => !l.includes(`${NAME}.css`)).join('\n');
        writeFileSync(aggregator, kept.trimEnd() + '\n', 'utf8');
    }
    if (existsSync(themeFile)) unlinkSync(themeFile);
}

test.beforeEach(cleanup);
test.afterAll(cleanup);

/** The primary colour the preview document resolves, read the way the page paints it. */
async function previewPrimary(page: Page): Promise<string> {
    return page.evaluate(() => {
        const doc = (document.querySelector('iframe') as HTMLIFrameElement).contentDocument!;
        return doc.defaultView!.getComputedStyle(doc.documentElement).getPropertyValue('--pdx-color-primary').trim();
    });
}

async function openTheme(page: Page, query: string): Promise<void> {
    await page.goto(`/packages/builder/index.html?mode=theme&component=button&scenario=button-variants${query}`);
    await page.waitForFunction(() => !!(globalThis as Record<string, unknown>).__pdx_builder);
}

test('the Save button writes the theme and registers it', async ({ page }) => {
    await openTheme(page, `&name=${NAME}&brand=%23c2185b&language=material`);

    await page.locator('[data-test="save-theme"]').click();

    const msg = page.locator('[data-test="save-msg"]');
    await expect(msg).toBeVisible();
    await expect(msg).toContainText('Saved');

    // Right after the save — mid-run, where the design suite would trip on it — the working tree's
    // custom themes are exactly what they were. The file went to the suite's own directory.
    expect(workingTreeSnapshot(), 'a builder test wrote under packages/design/src/themes/custom/').toEqual(workingTreeBefore);

    // The claim is about the file on disk, not about the toast.
    expect(existsSync(themeFile), `${themeFile} should exist — if it is in the working tree instead, the dev server on the test port was not started by this config (reuseExistingServer) and has no ${CUSTOM_THEMES_ENV}`).toBe(true);
    const css = readFileSync(themeFile, 'utf8');
    expect(css).toContain(`[pdx-theme="${NAME}"]`);
    expect(css).toContain('GENERATED by the PDX Builder');

    expect(readFileSync(aggregator, 'utf8')).toContain(`@import "./${NAME}.css"`);

    // And the new theme is offered immediately — no restart, no hand-edited list.
    const themes = await page.evaluate(() => (globalThis as any).__pdx_builder.themes());
    expect(themes.custom).toContain(NAME);
    expect(themes.all).toContain(NAME);
});

test('saving twice does not duplicate the import', async ({ page }) => {
    await openTheme(page, `&name=${NAME}&brand=%23c2185b`);

    await page.locator('[data-test="save-theme"]').click();
    await expect(page.locator('[data-test="save-msg"]')).toContainText('Saved');
    await page.evaluate(async () => await (globalThis as any).__pdx_builder.save());

    const imports = readFileSync(aggregator, 'utf8').split('\n')
        .filter(l => l.includes(`${NAME}.css`));
    expect(imports, 'the import must appear exactly once').toHaveLength(1);
});

test('a shipped theme name is refused — saving never overwrites what ships', async ({ page }) => {
    await openTheme(page, '&name=material&brand=%23c2185b');

    await page.locator('[data-test="save-theme"]').click();

    const msg = page.locator('[data-test="save-msg"]');
    await expect(msg).toBeVisible();
    await expect(msg).toContainText('shipped theme');
    expect(existsSync(resolve(customDir, 'material.css'))).toBe(false);
});

test('an invalid name is refused before anything is written', async ({ page }) => {
    await openTheme(page, '&name=Not%20A%20Name&brand=%23c2185b');

    await page.locator('[data-test="save-theme"]').click();
    await expect(page.locator('[data-test="save-msg"]')).toContainText('Invalid theme name');
});

test('the brand colour picker and the text field stay in step', async ({ page }) => {
    await openTheme(page, `&name=${NAME}&brand=%23c2185b`);

    const picker = page.locator('[data-test="knob-brand-picker"]');
    await expect(picker).toHaveValue('#c2185b');

    // An oklch() brand has no hex the picker can show; it must not corrupt the draft.
    await page.evaluate(async () => await (globalThis as any).__pdx_builder.setDraft({ brand: 'oklch(0.52 0.16 215)' }));
    const state = await page.evaluate(() => (globalThis as any).__pdx_builder.state());
    expect(state.draft.brand).toBe('oklch(0.52 0.16 215)');
    await expect(page.locator('[data-test="knob-brand"]')).toHaveValue('oklch(0.52 0.16 215)');
});

test('a saved theme actually RENDERS when picked — not just appears in the list', async ({ page }) => {
    // A save can report success, add the theme to the
    // dropdown, write both files — and still leave the tool inert, because the stylesheet
    // the preview loads was transformed before the theme existed. "It is in the list" is not
    // the claim; "picking it repaints the components" is.
    const brandHue = 46;   // #b3541e — an orange nothing else in the suite uses
    await page.goto(`/packages/builder/index.html?mode=theme&name=${NAME}&brand=%23b3541e&language=material`);
    await page.waitForFunction(() => !!(globalThis as Record<string, unknown>).__pdx_builder);

    await page.locator('[data-test="save-theme"]').click();
    await expect(page.locator('[data-test="save-msg"]')).toContainText('Saved');

    // The saved theme's stylesheet arrives LATE, on purpose. Under the full gate it sometimes
    // does, and the preview could be read before it lands. A delay here makes that the
    // normal case instead of a one-in-N, so a wait that is not the condition fails every time.
    // This is latency injected into the network, not a wait: nothing below sleeps.
    await page.route(`**/__pdx/custom-themes/${NAME}.css*`, async (route) => {
        await new Promise((r) => setTimeout(r, 1500));
        await route.continue();
    });

    // Component mode, the saved theme picked by name: nothing is injected here, so whatever
    // renders comes from the file on disk through the served stylesheet.
    await page.goto(`/packages/builder/index.html?component=button&scenario=button-variants&theme=${NAME}`);
    // The builder's own readiness (catalog and theme list in), then its own measurement. The
    // preview being MOUNTED is not the wait, because mounted is not themed: the sheet is a <link>
    // that lands on its own time. measure() is what an agent calls before reading a verdict, so
    // it is the claim worth holding: when it resolves, the picked theme is the one on screen.
    await expect(page.locator('html[data-builder-ready]')).toHaveCount(1);
    await expect(page.frameLocator('[data-test="preview"]').locator('html[data-pdx-ready]')).toHaveCount(1);
    await page.evaluate(async () => { await (globalThis as any).__pdx_builder.measure(); });

    expect(await previewPrimary(page), 'the saved theme must be the one rendering').toContain(` ${brandHue})`);

    // And it STAYS on screen. Every measurement re-applies the theme, and replacing the link with a
    // new cache-busting query each time would mean a re-fetch, and the default theme back on screen
    // until it lands — on every knob. The same theme in the same document keeps its sheet.
    const sheetHref = () => page.evaluate(() =>
        (document.querySelector('iframe') as HTMLIFrameElement).contentDocument!
            .getElementById('pdx-builder-custom-theme')?.getAttribute('href') ?? '');
    const before = await sheetHref();
    expect(before).toContain(`${NAME}.css?v=`);
    await page.evaluate(async () => { await (globalThis as any).__pdx_builder.measure(); });
    expect(await sheetHref(), 'a second measurement must not re-fetch the sheet').toBe(before);
});

test('a saved theme renders even when the theme list arrives after the preview', async ({ page }) => {
    // The other order of the same race. The preview is themed from the list of custom themes, and
    // the list is a request of its own: when the frame loads and measures first, the picked name is
    // not on it yet, no sheet is loaded — and the list landing afterwards must still put it in force.
    const brandHue = 46;
    await openTheme(page, `&name=${NAME}&brand=%23b3541e&language=material`);
    await page.locator('[data-test="save-theme"]').click();
    await expect(page.locator('[data-test="save-msg"]')).toContainText('Saved');

    // Latency injected into the network, as above: the list is what arrives last.
    await page.route('**/__pdx/themes', async (route) => {
        await new Promise((r) => setTimeout(r, 1500));
        await route.continue();
    });
    await page.goto(`/packages/builder/index.html?component=button&scenario=button-variants&theme=${NAME}`);
    await expect(page.locator('html[data-builder-ready]')).toHaveCount(1);

    // No measure() here: calling it would re-apply the theme and hide exactly this. The condition
    // itself is the wait.
    await expect.poll(() => previewPrimary(page), { message: 'the saved theme must end up rendering', timeout: 5000 })
        .toContain(` ${brandHue})`);
});

test('the regeneration hint in the saved file actually runs', async ({ page }) => {
    // A hint with the placeholders left in is worse than none: it looks pasteable.
    await openTheme(page, `&name=${NAME}&brand=%23b3541e&language=material&density=compact`);
    await page.locator('[data-test="save-theme"]').click();
    await expect(page.locator('[data-test="save-msg"]')).toContainText('Saved');

    const header = readFileSync(themeFile, 'utf8').split(/\r?\n/)[1];
    expect(header).toContain('--brand "#b3541e"');
    expect(header).toContain('--language material');
    expect(header).toContain('--density compact');
    expect(header, 'no unfilled placeholders').not.toMatch(/<[a-z]+>/);
});

test('theme mode does not offer a theme picker that the draft overrides', async ({ page }) => {
    // Two controls claiming the same thing, one of them stale, is a lie about what is on screen.
    await openTheme(page, `&name=${NAME}&brand=%23b3541e`);
    await expect(page.locator('[data-test="theme"]')).toHaveCount(0);
    await expect(page.locator('[data-test="previewing"]')).toContainText(NAME);
});

test('every control can be addressed without a snapshot ref', async ({ page }) => {
    // An agent driving this by position has to re-snapshot after every change; a stable
    // selector is what makes the surface scriptable at all.
    await openTheme(page, `&name=${NAME}&brand=%23b3541e`);
    for (const id of ['pdx-knob-name', 'pdx-knob-brand', 'pdx-knob-language', 'pdx-knob-density', 'pdx-knob-radius']) {
        await expect(page.locator(`#${id}`), id).toHaveCount(1);
    }
    // And each carries its own accessible name, not just an adjacent text node.
    await expect(page.locator('#pdx-knob-language')).toHaveAttribute('aria-label', 'Archetype');
});
