// GENERATED by packages/design/scripts/theme-coverage.mjs — do not edit by hand.
// Run `node packages/design/scripts/theme-coverage.mjs --emit` after changing a theme file.
//
// Which tokens each theme leaves inheriting from the base. A theme that does not set a token
// still renders — the value falls through to tokens.css — so the gap is invisible until someone
// compares two themes side by side. Whether a gap is deliberate is a design judgement per theme;
// this module only says where they are.

/** Tokens a majority of the 13 themes set (7 or more): what a theme is expected to have an opinion about. */
export const THEME_CONTRACT: readonly string[] = [
    '--pdx-breadcrumb-separator',
    '--pdx-button-hover-shadow',
    '--pdx-button-min-height',
    '--pdx-button-radius',
    '--pdx-card-style',
    '--pdx-color-accent',
    '--pdx-color-accent-text',
    '--pdx-color-bg',
    '--pdx-color-border',
    '--pdx-color-border-strong',
    '--pdx-color-focus',
    '--pdx-color-inset',
    '--pdx-color-primary',
    '--pdx-color-primary-hover',
    '--pdx-color-primary-text',
    '--pdx-color-surface',
    '--pdx-color-warning',
    '--pdx-density-factor',
    '--pdx-focus-ring',
    '--pdx-font-heading',
    '--pdx-font-mono',
    '--pdx-font-sans',
    '--pdx-gray-100',
    '--pdx-gray-200',
    '--pdx-gray-50',
    '--pdx-gray-800',
    '--pdx-gray-900',
    '--pdx-gray-950',
    '--pdx-hue-accent',
    '--pdx-hue-primary',
    '--pdx-input-min-height',
    '--pdx-input-style',
    '--pdx-radius-lg',
    '--pdx-radius-md',
    '--pdx-radius-sm',
    '--pdx-radius-xl',
    '--pdx-shadow-color',
    '--pdx-shadow-lg',
    '--pdx-shadow-md',
    '--pdx-shadow-sm',
    '--pdx-shadow-xl',
    '--pdx-tab-indicator',
    '--pdx-tab-indicator-size',
    '--pdx-table-header-border-color',
    '--pdx-table-header-border-width',
    '--pdx-table-header-color',
    '--pdx-table-header-letter-spacing',
    '--pdx-table-header-transform',
    '--pdx-table-header-weight',
];

/** Per theme, the contract tokens it does not set. 'neutral' is the base and has no entry. */
export const THEME_INHERITED: Readonly<Record<string, readonly string[]>> = {
    'corporate': ['--pdx-button-hover-shadow', '--pdx-color-warning', '--pdx-gray-200', '--pdx-gray-800', '--pdx-shadow-xl', '--pdx-table-header-color', '--pdx-table-header-letter-spacing', '--pdx-table-header-transform', '--pdx-table-header-weight'],
    'cupertino': ['--pdx-button-hover-shadow'],
    'cyberpunk': ['--pdx-color-bg', '--pdx-color-border', '--pdx-color-border-strong', '--pdx-color-inset', '--pdx-color-surface', '--pdx-color-warning', '--pdx-table-header-border-width', '--pdx-table-header-weight'],
    'editorial': ['--pdx-color-border', '--pdx-color-border-strong', '--pdx-color-warning', '--pdx-shadow-color', '--pdx-table-header-color'],
    'fluent': ['--pdx-button-hover-shadow', '--pdx-tab-indicator', '--pdx-table-header-border-width'],
    'glass': ['--pdx-breadcrumb-separator', '--pdx-button-min-height', '--pdx-color-warning', '--pdx-density-factor', '--pdx-font-mono', '--pdx-input-min-height', '--pdx-shadow-color', '--pdx-tab-indicator-size'],
    'material': ['--pdx-density-factor', '--pdx-font-mono', '--pdx-table-header-border-color', '--pdx-table-header-border-width'],
    'metro': ['--pdx-button-hover-shadow', '--pdx-table-header-color'],
    'neumorphic': ['--pdx-color-bg', '--pdx-color-border', '--pdx-color-border-strong', '--pdx-color-inset', '--pdx-color-surface', '--pdx-color-warning', '--pdx-focus-ring', '--pdx-font-mono', '--pdx-tab-indicator-size'],
    'playful': ['--pdx-button-min-height', '--pdx-color-border', '--pdx-color-border-strong', '--pdx-color-inset', '--pdx-density-factor', '--pdx-font-mono', '--pdx-input-min-height', '--pdx-tab-indicator-size', '--pdx-table-header-border-width', '--pdx-table-header-letter-spacing', '--pdx-table-header-weight'],
    'pragmatic': ['--pdx-button-min-height', '--pdx-density-factor', '--pdx-input-min-height', '--pdx-tab-indicator-size'],
    'pragmatic-gold': ['--pdx-button-min-height', '--pdx-density-factor', '--pdx-input-min-height', '--pdx-tab-indicator-size'],
};

/** The contract tokens a shipped theme inherits from the base, or [] for an unknown name. */
export function inheritedFromBase(theme: string): readonly string[] {
    return THEME_INHERITED[theme] ?? [];
}
